sonar.projectKey=HomaraFrontend
sonar.organization=homara

sonar.sources=app
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.mts
sonar.typescript.file.suffixes=.ts,.tsx,.cts,.mts

sonar.exclusions=tests/**,**/*.test.*
sonar.coverage.exclusions=**/*.tsx,**/*.css,app/lib/translations.ts,app/lib/locales/**
sonar.cpd.exclusions=app/lib/translations.ts,app/lib/locales/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
